# Generated by Django 3.2.2 on 2021-05-21 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_lead_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='organisation',
        ),
    ]
